export const data1 = [
  {
    _id: "63274c9dacd4ceaf5badf2fc",
    code: "18IHS701",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "HS",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Professional Ethics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9dacd4ceaf5badf325",
    code: "18IPC702",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PC",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Cryptography and Network Security",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9dacd4ceaf5badf33e",
    code: "18IPC703",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PC",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Internet of Things and its Applications",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf360",
    code: "18IPE701",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Data Mining and Data Warehousing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf37d",
    code: "18IPE702",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Wireless Sensor Networks",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf39e",
    code: "18IPE703",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Software Testing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf3bb",
    code: "18IPE704",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Software Project Management",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf3d6",
    code: "18IPE705",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Software Quality Assurance",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf3f5",
    code: "18IPE706",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Enterprise Resource Planning",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf410",
    code: "18IPE707",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Intellectual Property Rights",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf42a",
    code: "18IPE708",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Information Retrieval",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9eacd4ceaf5badf443",
    code: "18IPE709",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Embedded System",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9facd4ceaf5badf46e",
    code: "18IPE710",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Cloud Computing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9facd4ceaf5badf48e",
    code: "18IPE711",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Advanced Data Structures",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9facd4ceaf5badf4b0",
    code: "18IPE712",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Foundations of Information Security",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9facd4ceaf5badf4de",
    code: "18IPE713",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Distributed Systems",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9facd4ceaf5badf502",
    code: "18IPE714",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Soft Computing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9facd4ceaf5badf527",
    code: "18IPE715",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "XML and Web Services",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9facd4ceaf5badf539",
    code: "18IPE716",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Semantic Web",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274c9facd4ceaf5badf556",
    code: "18IPE717",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Service Oriented Architecture",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf586",
    code: "18IPE718",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Virtualization Techniques",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf5a4",
    code: "18IPE719",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Fundamentals of Automata Theory",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf5be",
    code: "18IPE720",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Virtual and Augmented Reality",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf5dd",
    code: "18IPE721",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Introduction to Natural Language Processing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf5fb",
    code: "18IPE722",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Artificial Intelligence and Applications",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf610",
    code: "18IPE723",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Mobile Computing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf630",
    code: "18IPE724",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Human Computer Interface",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf645",
    code: "18IPE725",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Social Network Analysis",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca0acd4ceaf5badf658",
    code: "18IPE726",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Foundations of Image Processing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca1acd4ceaf5badf66f",
    code: "18IPE727",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Pervasive Computing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca1acd4ceaf5badf685",
    code: "18IPE728",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Software Defined Networking",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca1acd4ceaf5badf698",
    code: "18IPE729",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Computer Graphics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca1acd4ceaf5badf6af",
    code: "18IPE730",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Data Analytics*",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca5acd4ceaf5badf8a1",
    code: "18COE701",
    __v: 0,
    branch: "C",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Climate Change and Adaptation",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca5acd4ceaf5badf8b5",
    code: "18COE702",
    __v: 0,
    branch: "C",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Disaster Management and Mitigation",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca5acd4ceaf5badf8cd",
    code: "18COE703",
    __v: 0,
    branch: "C",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Energy Efficient Buildings",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca5acd4ceaf5badf8f7",
    code: "18MOE704",
    __v: 0,
    branch: "M",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Nanotechnology and Surface Engineering",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca5acd4ceaf5badf90c",
    code: "18MOE705",
    __v: 0,
    branch: "M",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Mechatronics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca5acd4ceaf5badf924",
    code: "18MOE706",
    __v: 0,
    branch: "M",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Renewable Energy Sources",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca5acd4ceaf5badf939",
    code: "18EOE707",
    __v: 0,
    branch: "E",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Renewable Power Generation Systems",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca5acd4ceaf5badf94e",
    code: "18EOE708",
    __v: 0,
    branch: "E",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Electric Vehicles",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca6acd4ceaf5badf962",
    code: "18EOE709",
    __v: 0,
    branch: "E",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Smart Grid Systems",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca6acd4ceaf5badf97a",
    code: "18LOE710",
    __v: 0,
    branch: "L",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Mobile Communication",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca6acd4ceaf5badf99a",
    code: "18LOE711",
    __v: 0,
    branch: "L",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Introduction to VLSI System Design",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca6acd4ceaf5badf9bb",
    code: "18LOE712",
    __v: 0,
    branch: "L",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Microcontroller and Applications",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca6acd4ceaf5badf9d8",
    code: "18POE713",
    __v: 0,
    branch: "P",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Rapid Prototyping",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca6acd4ceaf5badf9ed",
    code: "18POE714",
    __v: 0,
    branch: "P",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Managerial Economics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca6acd4ceaf5badfa0b",
    code: "18POE715",
    __v: 0,
    branch: "P",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Hydraulics and Pneumatics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfa38",
    code: "18NOE716",
    __v: 0,
    branch: "N",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Measurement  and Control",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfa49",
    code: "18NOE717",
    __v: 0,
    branch: "N",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Industrial Automation",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfa61",
    code: "18NOE718",
    __v: 0,
    branch: "N",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Virtual Instrumentation",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfa7b",
    code: "18SOE719",
    __v: 0,
    branch: "S",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Programming in Java",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfa8b",
    code: "18SOE720",
    __v: 0,
    branch: "S",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Cyber Security",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfa9f",
    code: "18SOE721",
    __v: 0,
    branch: "S",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Network Essentials",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfad4",
    code: "18IOE722",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Programming in Python",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfafb",
    code: "18IOE723",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Big Data Science",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca7acd4ceaf5badfb15",
    code: "18IOE724",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Object Oriented Programming Using C++",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca8acd4ceaf5badfb38",
    code: "18BOE725",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Computational Biology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca8acd4ceaf5badfb5f",
    code: "18BOE726",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Biology for Engineers",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca8acd4ceaf5badfb7d",
    code: "18BOE727",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "OE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Fundamentals of Bioengineering",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca8acd4ceaf5badfbbb",
    code: "18IPC707",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "PC",
    credits: 1.5,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Internet of Things Laboratory  ",
    total: 0,
    tutorial: 0,
    type: "Practical",
  },
  {
    _id: "63274ca8acd4ceaf5badfc1c",
    code: "18IEE708",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "EEC",
    credits: 4,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Mini Project",
    total: 0,
    tutorial: 0,
    type: "Practical",
  },
  {
    _id: "63274ca8acd4ceaf5badfc39",
    code: "18BHS701",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Technology Management ",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca8acd4ceaf5badfc50",
    code: "18BPC702",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Downstream Processing",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca8acd4ceaf5badfc6a",
    code: "18BPE701",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Biofuels",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfc96",
    code: "18BPE702",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Biopolymer Technology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfcbb",
    code: "18BPE703",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Industrial Hazard Management",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfcd8",
    code: "18BPE704",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Food Process Engineering",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfcfa",
    code: "18BPE705",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Medical Biotechnology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfd19",
    code: "18BPE706",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Marine Biotechnology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfd3a",
    code: "18BPE707",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Plant Biotechnology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfd5a",
    code: "18BPE708",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Cancer Biology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfd74",
    code: "18BPE709",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Environmental Biotechnology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274ca9acd4ceaf5badfd93",
    code: "18BPE710",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Molecular Pathogenesis",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfdaf",
    code: "18BPE711",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Nanobiotechnology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfdd8",
    code: "18BPE712",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Animal Biotechnology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfe00",
    code: "18BPE713",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Genomics and Proteomics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfe19",
    code: "18BPE714",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Mathematical and Numerical Methods for Biotechnology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfe42",
    code: "18BPE715",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Bioentrepreneurship",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfe63",
    code: "18BPE716",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Immunotechnology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfe93",
    code: "18BPE717",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Biopharmaceutical Technology",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfea9",
    code: "18BPE718",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Bioprocess Economics and Plant Design ",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274caaacd4ceaf5badfebd",
    code: "18BPE719",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Tissue Engineering",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274cabacd4ceaf5badfece",
    code: "18BPE720",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Metabolic Engineering",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274cabacd4ceaf5badfee9",
    code: "18BPE721",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Protein Engineering",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274cabacd4ceaf5badff00",
    code: "18BPE722",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Pharmacogenomics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274cabacd4ceaf5badff32",
    code: "18BPE723",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Genetics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274cabacd4ceaf5badff41",
    code: "18BPE724",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PE",
    credits: 3,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Biostatistics",
    total: 0,
    tutorial: 0,
    type: "Theory",
  },
  {
    _id: "63274cb4acd4ceaf5bae064e",
    code: "18BPC707",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "PC",
    credits: 2,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Downstream Processing Laboratory",
    total: 0,
    tutorial: 0,
    type: "Practical",
  },
  {
    _id: "63274cb4acd4ceaf5bae0670",
    code: "18BEE708",
    __v: 0,
    branch: "B",
    ca: 0,
    category: "EEC",
    credits: 4,
    lecture: 0,
    practical: 0,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "Mini Project",
    total: 0,
    tutorial: 0,
    type: "Practical",
  },
  {
    _id: "632aee0ce030c6c8b7bd296d",
    code: "18IHE706",
    __v: 0,
    branch: "I",
    ca: 0,
    category: "HE",
    credits: 0,
    lecture: 2,
    practical: 1,
    regulation: 2018,
    requirement: "Core",
    sem: 0,
    semester: 7,
    title: "GCT ERP Portal",
    total: 0,
    tutorial: 0,
    type: "Practical",
  },
];
